### ISSUE TITLE
The work's ability on adding/removing/changing objects

### ISSUE THREAD

**Issue by xiao10ma** [Friedrich-M/Instruct-4D-to-4D#2]
Hi Linzhan,

Thank you for your amazing work on Instruct-4d-to-4d! I have a question regarding the model's ability to handle instructions like adding, removing, or changing objects. Have you tested these types of instructions? In my experience, the model seems to struggle with them, and I'm wondering if this is a known limitation or if there are specific settings that could improve the results.

Thanks again for your great work!

**Comment by Friedrich-M** [comment]
Thanks for your interest in our work! Our method relies on the Instruct-Pix2Pix to conduct the editing. Instructions like "Adding, removing, and changing" are challenging for IP2P. 

I recommend taking one of your training views and trying to edit it in 2D firstly with InstructPix2Pix, which can be done at [this](https://huggingface.co/spaces/timbrooks/instruct-pix2pix) HuggingFace space. More tips on getting a good edit can be found [here](https://github.com/timothybrooks/instruct-pix2pix#tips).

You can also try replacing the IP2P with ControlNet V1.1 and using conditions like Mask to guide the editing process.

Also, for the object-level editing, you could refer to [AnyDoor](https://ali-vilab.github.io/AnyDoor-Page/), which focuses on Zero-shot Object-level Image Customization.

**Comment by xiao10ma** [comment]
Hi @Friedrich-M, thank you for your reply. I’m wondering, if I replace IP2P with ControlNet V1.1 or AnyDoor, would the anchor-aware attention module in your work still generalize well to these models (ControlNet V1.1 or AnyDoor)?

**Comment by Friedrich-M** [comment]
I have also implemented the anchor-aware attention module for ControlNet and it is easy to transfer. You can refer to https://github.com/YBYBZhang/ControlVideo and https://github.com/thu-ml/controlvideo for the implementation.

I have checked the AnyDoor pipeline, and it is also practical to implement the anchor-aware attention module by modifying the UNet structure.
<img width="1013" alt="image" src="https://github.com/user-attachments/assets/6ddcc69c-9e89-4319-b95b-8ff93408632c">

It is recommended first reading the [Turn-A-Video](https://tuneavideo.github.io/) to be familiar with Zero-Shot Video Editing.

If you find those models do not satisfy your requirement, you could refer to https://github.com/showlab/Awesome-Video-Diffusion for some specific video editing models.

**Comment by xiao10ma** [comment]
Thank you so much for your help!!!
